/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.dao;
import ENTITAS.entitas;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author PUI05
 */
public class UTAMA_ extends javax.swing.JFrame {

    /**
     * Creates new for UTAMA_
     */
    static String admin = "";

    public UTAMA_(String id_admin) {
        initComponents();
        id_admin_txt.setText(id_admin);
        kode_nota();
        refresh();
        kalender();
    }
    int file = 0;
    entitas en = new entitas();
    koneksi kon = new koneksi();
    dao dao = new dao(kon.getconnection());
    List<entitas> list = new ArrayList();
    List<entitas> list2 = new ArrayList();
    int totalSeluruh = 0;
    int kembalian = 0;
    int refund = 0;

    ArrayList<String> tmp_kode = new ArrayList();
    ArrayList<String> tmp_menu = new ArrayList();
    ArrayList<Integer> tmp_harga = new ArrayList();
    ArrayList<Integer> tmp_jumlah = new ArrayList();// jumlah per item
    ArrayList<Integer> tmp_total = new ArrayList();// total per item

    public void kalender() {
        new Thread() {
            public void run() {
                while (true) {
                    Calendar kal = new GregorianCalendar();
                    int tahun = kal.get(Calendar.YEAR);
                    int bulan = kal.get(Calendar.MONTH) + 1;
                    int hari = kal.get(Calendar.DAY_OF_MONTH);
                    int jam = kal.get(Calendar.HOUR_OF_DAY);
                    int menit = kal.get(Calendar.MINUTE);
                    int detik = kal.get(Calendar.SECOND);
                    String tanggal = hari + " - " + bulan + " - " + tahun;
                    String waktu = jam + " : " + menit + " : " + detik;
                    tanggal_display.setText("Tanggal : " + tanggal);
                    jam_display.setText("Jam : " + waktu);
                }
            }
        }.start();
    }

    public void init() {//fungsi inisial untuk mengembalikan ke null
        kodetxt.setText("");
        namatxt.setText("");
        hargatxt.setText("");
        jumlahtxt.setText("");
        totaltxt.setText("");
        bayartxt.setText("");
        kembalitxt.setText("");
        tmp_total.removeAll(tmp_total);
        tmp_kode.removeAll(tmp_kode);
        tmp_menu.removeAll(tmp_menu);
        tmp_harga.removeAll(tmp_harga);
        tmp_jumlah.removeAll(tmp_jumlah);
        totalSeluruh = 0;
        String[][] kosong = new String[1][4];
        table_belanja.setModel(new DefaultTableModel(kosong, new String[]{"Menu", "Harga", "Jumlah", "Total"}));
    }

    public void kode_nota() {//fungsi untuk menambahkan no nota otomatis
        list = dao.getNoNota();
        String[] dat = new String[1];
        int id = 0;
        int j = 0;
        for (entitas li : list) {
            dat[j] = li.getId_nota() + "";
            j++;
        }
        int g = 0;
        if (dat[g] == "") {
            id = 0;// apabila masih kosong di database
        } else {
            id = Integer.parseInt(dat[g]);
        }

        String kode_transaksi = ++id + "";
        kode_nota_txt.setText(kode_transaksi);
    }

    public int refresh() {// mendapatkan seluruh data menu
        list = dao.getMenu();
        String[][] data = new String[list.size()][3];
        int i = 0;
        int result = 0;
        for (entitas li : list) {
            data[i][0] = li.getKode_menu();
            data[i][1] = li.getNama_menu();
            data[i][2] = li.getHarga_menu() + "";
            i++;
        }
        String coba = String.valueOf(result);
        tabel_menu.setModel(new DefaultTableModel(data, new String[]{
            "Kode Menu", "Menu", "Harga"}));
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_menu = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_belanja = new javax.swing.JTable();
        caritxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_admin_txt = new javax.swing.JTextField();
        kode_nota_txt = new javax.swing.JTextField();
        kodetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        namatxt = new javax.swing.JTextField();
        hargatxt = new javax.swing.JTextField();
        jumlahtxt = new javax.swing.JTextField();
        okbtn = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        totaltxt = new javax.swing.JTextField();
        bayartxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Print = new javax.swing.JButton();
        kembalitxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tanggal_display = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jam_display = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaksi Kasir");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tabel_menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tabel_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Menu", "Menu", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_menu.setFillsViewportHeight(true);
        tabel_menu.setFocusCycleRoot(true);
        tabel_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_menuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_menu);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Cari :");

        table_belanja.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        table_belanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Harga", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_belanja.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table_belanja.setFillsViewportHeight(true);
        table_belanja.setFocusCycleRoot(true);
        jScrollPane1.setViewportView(table_belanja);

        caritxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        caritxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caritxtKeyReleased(evt);
            }
        });

        jLabel1.setText("ID Admin");

        jLabel2.setText("Kode Tranksaksi");

        id_admin_txt.setEnabled(false);

        kode_nota_txt.setEnabled(false);

        kodetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Daftar Belanja :");

        namatxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        hargatxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jumlahtxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        okbtn.setBackground(new java.awt.Color(0, 153, 51));
        okbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        okbtn.setForeground(new java.awt.Color(255, 255, 255));
        okbtn.setText("+");
        okbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbtnActionPerformed(evt);
            }
        });

        btn_batal.setBackground(new java.awt.Color(255, 51, 51));
        btn_batal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        totaltxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });

        bayartxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bayartxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayartxtKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Bayar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Total");

        Print.setBackground(new java.awt.Color(51, 102, 255));
        Print.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Print.setForeground(new java.awt.Color(255, 255, 255));
        Print.setText("Ok/Cetak");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Kembali");

        jLabel6.setText("Kode Menu :");

        jLabel9.setText("Nama Menu");

        jLabel10.setText("Harga Menu");

        jLabel11.setText("Jumlah");

        tanggal_display.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggal_display.setText("TANGGAL");

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*Klik pada tabel daftar Menu diatas");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Daftar Menu :");

        jam_display.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jam_display.setText("jam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(caritxt)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(58, 58, 58)
                                        .addComponent(bayartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(36, 36, 36)
                                        .addComponent(kembalitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(id_admin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(kode_nota_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tanggal_display, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jam_display, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hargatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(okbtn)))))
                    .addComponent(jLabel14))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_admin_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggal_display))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(kode_nota_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jam_display)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel14))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(caritxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bayartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(kembalitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_batal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Print)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbtnActionPerformed

        //cek apabila uang bayar belum ditulis
        if (hargatxt.getText().equals("") || jumlahtxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Harga atau Jumlah tidak boleh kosong!", "Terjadi Kesalahan", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //variabel penampung
        int harga = Integer.parseInt(hargatxt.getText());
        int jumlah = Integer.parseInt(jumlahtxt.getText());
        int total = harga * jumlah;

        totalSeluruh += total;// menghitung total keseluruhan

        tmp_kode.add(kodetxt.getText());
        tmp_menu.add(namatxt.getText());
        tmp_harga.add(harga);
        tmp_jumlah.add(jumlah);
        tmp_total.add(total);

        String[][] dataBelanja = new String[tmp_harga.size()][4];
        int i = 0;
        for (String enitas : tmp_kode) {
            dataBelanja[i][0] = tmp_menu.get(i);
            dataBelanja[i][1] = tmp_harga.get(i) + "";
            dataBelanja[i][2] = tmp_jumlah.get(i) + "";
            dataBelanja[i][3] = tmp_total.get(i) + "";
            i++;
        }

        totaltxt.setText(totalSeluruh + "");
        table_belanja.setModel(new DefaultTableModel(dataBelanja, new String[]{"Menu", "Harga", "Jumlah", "Total"}));

    }//GEN-LAST:event_okbtnActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        init();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        try {
            // masuk data nota
            entitas e = new entitas();
            e.setId_nota(Integer.parseInt(kode_nota_txt.getText()));
            e.setTotal(totalSeluruh);
            e.setId_karyawan(Integer.parseInt(id_admin_txt.getText()));
            dao.inputNota(e);

            File file = new File("D://nota");
            if (!file.exists()) {
                file.mkdir();
            }
            FileWriter fw = new FileWriter("D://nota//" + kode_nota_txt.getText() + ".txt");
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("No Transaksi : " + kode_nota_txt.getText());
            bw.newLine();
            bw.write("_________________________________");
            bw.newLine();

            String header = String.format("%-16s %-16s %-16s %-16s", "Menu", "Harga",
                    "Jumlah", "Total");
            bw.write(header);
            bw.newLine();

            entitas ee = new entitas();
            for (int i = 0; i < tmp_kode.size(); i++) {
                String data = String.format("%-15s %-15s %-15s %-15s",
                        tmp_menu.get(i), tmp_harga.get(i),
                        tmp_jumlah.get(i), tmp_total.get(i));
                bw.write(data);

                bw.newLine();
                // masuk data transaksi

                ee.setId_nota(Integer.parseInt(kode_nota_txt.getText()));
                ee.setKode_menu(tmp_kode.get(i));
                ee.setJumlah(tmp_jumlah.get(i));
                dao.inputTransaksi(ee);
            }

            bw.write("Total : " + totalSeluruh);
            bw.newLine();
            bw.write("Kembali : " + refund);
            JOptionPane.showMessageDialog(this, "Transaksi Berhasil!", "Info", JOptionPane.INFORMATION_MESSAGE);
            init();
            kode_nota();

            bw.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_PrintActionPerformed

    private void tabel_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_menuMouseClicked
        // TODO add your handling code here:
        kodetxt.setText(tabel_menu.getValueAt(tabel_menu.getSelectedRow(), 0).toString());
        namatxt.setText(tabel_menu.getValueAt(tabel_menu.getSelectedRow(), 1).toString());
        hargatxt.setText(tabel_menu.getValueAt(tabel_menu.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tabel_menuMouseClicked

    private void bayartxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayartxtKeyReleased
        // TODO add your handling code here:
        try {
            int uang = Integer.parseInt(bayartxt.getText());
            int totalBayar = Integer.parseInt(totaltxt.getText());
            refund = uang - totalBayar;
            kembalitxt.setText(refund + "");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bayartxtKeyReleased

    private void caritxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caritxtKeyReleased
        // TODO add your handling code here:
        list = dao.cariMenu(caritxt.getText());
        String[][] tmp = new String[list.size()][3];
        int i = 0;
        for (entitas c : list) {
            tmp[i][0] = c.getKode_menu();
            tmp[i][1] = c.getNama_menu();
            tmp[i][2] = c.getHarga_menu() + "";
            i++;
        }

        tabel_menu.setModel(new DefaultTableModel(tmp, new String[]{"Kode Menu", "Menu", "Harga"}));
    }//GEN-LAST:event_caritxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTAMA_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTAMA_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTAMA_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTAMA_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VIEW.UTAMA_(admin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Print;
    private javax.swing.JTextField bayartxt;
    private javax.swing.JButton btn_batal;
    private javax.swing.JTextField caritxt;
    private javax.swing.JTextField hargatxt;
    private javax.swing.JTextField id_admin_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jam_display;
    private javax.swing.JTextField jumlahtxt;
    private javax.swing.JTextField kembalitxt;
    private javax.swing.JTextField kode_nota_txt;
    private javax.swing.JTextField kodetxt;
    private javax.swing.JTextField namatxt;
    private javax.swing.JButton okbtn;
    private javax.swing.JTable tabel_menu;
    private javax.swing.JTable table_belanja;
    private javax.swing.JLabel tanggal_display;
    private javax.swing.JTextField totaltxt;
    // End of variables declaration//GEN-END:variables
}
